### ISSUE TITLE
母鸡重启后docker小鸡的ssh无法连接

### ISSUE THREAD

**Issue by f3liiix** [oneclickvirt/docker#11]
机器重启后，我使用 docker start $(docker ps -aq) 启动了所有docker小鸡，但是，ssh均无法连接，小鸡上架的服务也连接不上。但是我在母鸡上可以使用docker命令进入小鸡。

请问是什么问题？或者如何排查问题？

**Comment by spiritLHLS** [comment]
默认挂起命令没有带上ssh自动启动命令，我改改，wait

**Comment by f3liiix** [comment]
SSH没自动启动，小鸡里的服务也不通吗？

**Comment by f3liiix** [comment]
我看提交了，弄好了吗？大佬。那我现在这个该怎么启动ssh呢？

**Comment by spiritLHLS** [comment]
已修复，你需要重新开小鸡了，因为启动命令修改了

**Comment by spiritLHLS** [comment]
容器在启动了的情况下无法修改容器启动命令的

**Comment by f3liiix** [comment]
天呐，那我这些小鸡里都配置了挺多服务怎么整，融合怪大佬，有没有方法可以保留docker数据实现的？

**Comment by spiritLHLS** [comment]
> 天呐，那我这些小鸡里都配置了挺多服务怎么整，融合怪大佬，有没有方法可以保留docker数据实现的？

额，不迁移那你只能每个容器进去执行 service ssh restart 

没有办法在不破坏容器的情况下修改成自动重启ssh服务的
