### ISSUE TITLE
一键启动安卓容器失败

### ISSUE THREAD

**Issue by jJuXZJGd** [oneclickvirt/docker#8]
目前Ubuntu20.04，内核版本5.4。进入scrcpyweb后页面白屏。请问脚本测试系统的版本和内核版本？想按照你的环境测试一下

**Comment by spiritLHLS** [comment]
明天有空我看看，好久没用了

**Comment by spiritLHLS** [comment]
![图片](https://github.com/oneclickvirt/docker/assets/103393591/d5969ad6-3e71-4198-a0a6-43b14224dfe0)
![图片](https://github.com/oneclickvirt/docker/assets/103393591/eaacb364-3b32-4715-8481-b9b4b2fa0f96)

明天有空我再优化一下守护进程，就好了，目前测试screen挂起 ws-scrcpy 是成功的
运行环境： Ubuntu 20.04 开设都使用默认值

**Comment by spiritLHLS** [comment]
已修复

**Comment by spiritLHLS** [comment]
删掉原始的所有.sh文件后，Ubuntu 20.04 开设时全部使用默认的回车，我测试没问题了
