### ISSUE TITLE
docker ipv6 网络问题

### ISSUE THREAD

**Issue by secflag** [oneclickvirt/docker#9]
特殊需求：vps 有一个ipv4 地址和一个ipv6  /64 网段，使用大佬的脚本自动分配的ipv6地址可以访问互联网，但是出口ipv6地址是宿主机的ipv6，并且从互联网上无法访问容器内的ipv6地址，大佬有没有办法配置让每个容器都有自己独立的公网ipv6 并且可以使用该ipv6地址访问互联网和通过该ipv6被访问，无需net 转发。

**Comment by spiritLHLS** [comment]
尝试过，但我没办法解决，按照你这种想法，你需要按照
https://www.spiritysdx.top/20230829/
我曾经的思路进行你自己的修改
